public class Test {
  /**
   * @description Contact map that represents the trigger.oldMap map passed in
   from the trigger
   */
   private Map<Id, Contact> oldContactMap = new Map<Id, Contact>();

   /**
    * @description Contact list that represents the trigger.new list passed in from the
    trigger
    */
    private List<Contact> currentContactList = new List<Contact>();

    /**
     * description This is a generic description
     * @example
     * determineListForContacts();
     */
     private void determineListForContacts();
}